### ISSUE TITLE
CSS injection

### ISSUE THREAD

**Issue by MichalBryxi** [mmckeaveney/theme-it#10]
Assume following situation:

 - An app allows the user to change the CSS theme
 - An app puts the currently selected theme to query parameter
 - Is it then possible for a malicious user to craft URL in a way that it completely changes the contents of the page for other users? Via shared URL?

Tried to [craft an example](https://gist.github.com/MichalBryxi/c0c9bcc04b2bc288a36e758ef6469fc8) by gathering the theme name from HTML input field rather from query param (sorry my React-fu is weak). It's not working, but you can see the concept.

**Comment by shogunpurple** [comment]
Yep @MichalBryxi I think this is an issue. I will test it out and try and break it. If so I will need to sanitize the CSS input before rendering it into the DOM
